### ISSUE TITLE
SDK diagnostic data is missing when `generate_diagnostic_data` is called via `execute_command` API

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/breez-sdk#1048]

**Comment by dangeross** [comment]
It seems to work through the CLI and swift uniffi (tested on RN iOS). Could it be a limitation of Flutter? It can be a fairly large string response

**Comment by erdemyerebasmaz** [comment]
> It seems to work through the CLI and swift uniffi (tested on RN iOS). Could it be a limitation of Flutter? It can be a fairly large string response

@dangeross CLI implementation calls `generate_diagnostic_data` directly, when it comes to uniffi, I believe you're calling `generate_diagnostic_data` directly as well. The issue is when this command is called via `execute_command` / `execute_dev_command` API's.

See [implementation](https://github.com/breez/breez-sdk/blob/0092c0957f034507f287bff18abcdcd00f8a7584/libs/sdk-core/src/greenlight/node_api.rs#L1549C13-L1552C14) for missing `generate_sdk_diagnostic_data` call.

**Comment by dangeross** [comment]
@erdemyerebasmaz I tested via `execute_dev_command`

**Comment by dangeross** [comment]
Ignore me, I misread the issue.
