### ISSUE TITLE
sdk: Add pre-flight checks for payments

### ISSUE THREAD

**Issue by cdecker** [breez/breez-sdk#1057]
The Greenlight plugin implements a number of pre-flight checks:

 - Check that the sum of all available channel balances exceeds the amount to be sent, if not abort.
 - Wait for enough available channel balances to come online before calling `pay`. On a 30s timeout abort with an error
 - Check the invoice expiry. If the invoice is expired, abort.

All of these are considered to be user-errors (well, the slow channel reconnect could be indicative of several problems, so those trigger introspections from us), and as such they could and likely should be handled on the client side already.

Since the SDK has a very good idea of the channel state, thanks to the background sync of node metadata, the first and last check would be trivial to implement, and would result in an even faster feedback for users.

**Comment by cdecker** [comment]
We have a number of further pre-flight checks that we're looking to either upstream into CLN, or keep in gl-plugin. If we have further validation that would warrrant checking on the client we'll share them of course :-)

**Comment by roeierez** [comment]
Makes sense.
