### ISSUE TITLE
Return a specific error when onchain funds are not enough to pay for onchain fees

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#1059]
At the moment, `prepare_redeem_onchain_funds` returns `NodeError::generic("Insufficient funds to pay fees")` when funds are not enough to pay for onchain fees. It would be useful if a specific error (e.g. `NodeError:InsufficientFundsForFees`) was returned so that SDK integrators could react without having to parse the error string.

**Comment by roeierez** [comment]
@danielgranhao makes sense.
How about `NodeError::InsufficientFunds` ? sounds a bit more generic and still usefull.

**Comment by danielgranhao** [comment]
@roeierez SGTM
