### ISSUE TITLE
Add methods to NodeAPI for signmessage and checkmessage

### ISSUE THREAD

**Issue by dangeross** [breez/breez-sdk#109]
It would be great if the NodeAPI could expose methods to perform signmessage and checkmessage on the Greenlight node.

https://lightning.readthedocs.io/lightning-checkmessage.7.html
https://lightning.readthedocs.io/lightning-signmessage.7.html

**Comment by dangeross** [comment]
Even though I originally asked about this because of LNURL-auth, I think there are still several other use cases where it would be nice to at least sign a message, so that a 3rd party service can verify you are in control of the node. I rough example would be embedding a 3rd party web service (like an exchange) into an application using WebLN.

**Comment by lnd3v** [comment]
FYI the endpoints are disabled. I've tried signing the mesage in a variety of ways, but all result in the wrong pubkey. I've posted about this in the greenlight chat. Let's see what comes next week.

**Comment by JssDWt** [comment]
Fixed in https://github.com/breez/breez-sdk/pull/319
