### ISSUE TITLE
Send notifications to multiple endpoints

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/breez-sdk#112]

**Comment by JssDWt** [comment]
@erdemyerebasmaz Can you put a description what this issue means?

**Comment by erdemyerebasmaz** [comment]
> @erdemyerebasmaz Can you put a description what this issue means?

I guess this no longer belongs to this repository and can be closed. We created this issue before we published notify repository.

Our tests for offline payments involved sending a notification to a single device(_specific node id-associated device token_). This was for broadcasting notifications to all users or a subgroup of users(_topic messaging_) of NDS(_notification delivery service_) as I recall.

**Comment by ok300** [comment]
As discussed, closing
