### ISSUE TITLE
sdk-react-native iOS/Android example app broken

### ISSUE THREAD

**Issue by xsats** [breez/breez-sdk#194]
Hey, just tried to take `react-native-sdk` for a spin but seems as though it's not currently linking by default (both iOS and Android failing to compile). 

What's the current state of the RN lib - is this expected (is the framework still WIP #96)?

**Comment by kingonly** [comment]
https://www.npmjs.com/package/@breeztech/react-native-breez-sdk

**Comment by roeierez** [comment]
Should be working now. Thanks for reporting.
