### ISSUE TITLE
Publish dotnet bindings to c#

### ISSUE THREAD

**Issue by Kukks** [breez/breez-sdk#225]
The gl-client is not reachable publicly so one cannot easily build the bindings. Please publish a nuget package for the C# bindings.

Ideally, with windows support too (#217 )

**Comment by JssDWt** [comment]
@Kukks I'm working on a nuget package. Do you intend to work with that nuget package? And if so, which platform do you want to support? I'm asking because the nuget package needs binaries for each supported platform included.

**Comment by Kukks** [comment]
> @Kukks I'm working on a nuget package. Do you intend to work with that nuget package? And if so, which platform do you want to support? I'm asking because the nuget package needs binaries for each supported platform included.

I would target as many as possible. From a development perspective we work on mac Linux and windows. We currently deploy mostly to Linux but medium long term will be to also deploy on mac, Linux, android, windows and ios

**Comment by JssDWt** [comment]
@Kukks There is a nuget package available: https://www.nuget.org/packages/Breez.Sdk

It currently supports the following platforms:
- win-x64
- linux-x64
- linux-arm64
- osx-x64
- osx-arm64

I'm going to close this issue, feel free to reopen, or open a new issue in case there's something you'd like to see.
