### ISSUE TITLE
Flutter: There's no stream for balance changes out of the box

### ISSUE THREAD

**Issue by JssDWt** [breez/breez-sdk#227]
We expose `nodeStateStream`, which contains the current balance on the node. But `nodeStateStream` doesn't receive an update when the balance has changed. You have to call `getNodeState` after sending/receiving in order to trigger an update on the `nodeStateStream`.

Maybe we can trigger updates to that stream on successful payment delivery and when an invoice has been paid out-of-the-box?

**Comment by roeierez** [comment]
Isn't it already implemented here? https://github.com/breez/breez-sdk/blob/main/libs/sdk-flutter/lib/breez_bridge.dart#L40

**Comment by JssDWt** [comment]
> Isn't it already implemented here?

Yes, you're right. I didn't see that.
