### ISSUE TITLE
send_payment returns Error: payment not found

### ISSUE THREAD

**Issue by JssDWt** [breez/breez-sdk#291]
send_payment returned this error after completion.
The invoice was successfully paid.

The error comes from here https://github.com/breez/breez-sdk/blob/4b382f2db45743b93fac5c7bc6de31d021a11aab/libs/sdk-core/src/breez_services.rs#L701

I don't have any logs unfortunately, other than the node id `03e673b5fe2c3a3f921d8fcf0d184d8a703786dff03ae729151e8aa6dec2ede030` and timestamp around block 796991.

I was using this commit
https://github.com/breez/breez-sdk/commit/4b382f2db45743b93fac5c7bc6de31d021a11aab

**Comment by roeierez** [comment]
After payment we pull the payments from greenlight and then search by hash for completed payments. My suspection is that the payment is still pending in greenlight (last phase of commit revocation still in progress maybe?).
Worth asking Christian if this theory makes sense.
Also I think we should change the call to search any payment by hash and not only completed

**Comment by JssDWt** [comment]
Should be fixed in https://github.com/breez/breez-sdk/pull/409
