### ISSUE TITLE
Publish Python package

### ISSUE THREAD

**Issue by ubbabeck** [breez/breez-sdk#332]
Discussed with Roei, I have added this task to my todos.

**Comment by massmux** [comment]
At the moment i want to use python, but still not able to get it running. some package would be very nice

**Comment by ubbabeck** [comment]
- [ ] Make CI 
- [ ] Automatically publish with new releases
- [ ] Create tests
- [ ] Publish to https://pypi.org/ using CI

**Comment by prusnak** [comment]
It would be great to have a Breez SDK package on PyPI.
Not having it blocks the inclusion of Breez-SDK as a funding source for LNbits.

**Comment by massmux** [comment]
Yes having the possibility to use breez-sdk as a funding source for LNBits would really be a game-changer. i totally agree

**Comment by prusnak** [comment]
This should not be closed yet - there is no Breez SDK package on PyPI. Please reopen.

**Comment by ok300** [comment]
Hey @prusnak , the package is available here: https://pypi.org/project/breez-sdk/
