### ISSUE TITLE
Update SDK service methods to return `SdkResult`

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk#336]
Change existing service from returning `anyhow::Result` to return `SdkResult`.

This migration is completed when the trait

https://github.com/breez/breez-sdk/blob/b8f1c490d99df82f2fd3a5b4ef7fcf9d2908d488/libs/sdk-core/src/error.rs#L41-L48

is not needed anymore.

A good way to find which method to migrate next is therefore to comment out that trait implementation, then run `cargo clippy` in `/libs/sdk-core` to see which service methods cause errors.

When all service methods are migrated, the trait above should be deleted.

Partially addressed in #298

**Comment by roeierez** [comment]
@dangeross can we close this?

**Comment by dangeross** [comment]
I just checked and all exposed methods except `prepare_refund` return SdkResult or a Result with a method specific error. I will make a PR to change `prepare_refund`.
