### ISSUE TITLE
Lower level CLN invoice commands

### ISSUE THREAD

**Issue by michael1011** [breez/breez-sdk#367]
When trying to implement features that go beyond a simple wallet, one hits roadblocks pretty quickly. I was trying to implement [LNURL for the Breez SDK](https://github.com/michael1011/clnurl/pull/1), but unfortunately, that is not possible because the `description_hash` of the invoices from the SDK can't be set.

I would propose exposing more fields of [the `create_invoice` function](https://github.com/breez/breez-sdk/blob/main/libs/sdk-core/src/greenlight/node_api.rs#L242).
Or exposing "dev" commands like `signinvoice` that would allow for getting an invoice with the `create_invoice` call, decoding, setting your own fields and signing again.

**Comment by ok300** [comment]
Have you already tried to use Breez SDK's built-in LNURL functionality?

https://sdk-doc.breez.technology/guide/lnurl.html

https://breez.github.io/breez-sdk/breez_sdk_core/#e-using-lnurl

**Comment by roeierez** [comment]
@michael1011 indeed lower level API is something we try to avoid to keep the sdk simple to use but we will add the necessary changes for a valid use case. Can you elaborate on the use case you are trying to implement? Once we understand it we promise to do our best to support it.

**Comment by JssDWt** [comment]
> @michael1011 indeed lower level API is something we try to avoid to keep the sdk simple to use but we will add the necessary changes for a valid use case. Can you elaborate on the use case you are trying to implement? Once we understand it we promise to do our best to support it.

Michael and I had a talk about this on Discord.
The main goal is to create a server side lnurl implementation. In order to do that, he needs a description hash in the invoice. The description hash did not automatically appear in the invoice through the greenlight rpc, possibly because the description is small. 

The way to work around that for Michael would be to sign the invoice created by `receive_payment` after some modifications to the invoice, so a `sign_invoice` function, or similar. Or have more options on the creation of an invoice, so the description hash could be set from there.

**Comment by roeierez** [comment]
Thanks for the explanation @JssDWt 
So ideally it makes sense to me that clightning will add support for passing this tag explicitly in the API ,(same as lnd does).
If you agree then let's open an issue for that?
Meantime I see two options:
1. Expose sign_invoice as requested here 
2. Add optional description hash parameter in the sdk receive_payment API and encode/sign internally as we already doing today (lfor lsp hints)
Option 2 is simpler for the user and will work seamlessly when clightning add the hash support.
What do you guys think?

**Comment by JssDWt** [comment]
> So ideally it makes sense to me that clightning will add support for passing this tag explicitly in the API ,(same as lnd does).
> If you agree then let's open an issue for that?

CLN already has a `deschashonly` flag in the [invoice call](https://docs.corelightning.org/reference/lightning-invoice). If exposed, that would fix Michael's problem. It is not exposed in Greenlight's `InvoiceRequest` currently.

CLN also doesn't support ONLY passing a description hash, so probably the `deschashonly` flag while passing the entire description to CLN will do the trick for lnurl.

**Comment by roeierez** [comment]
> CLN also doesn't support ONLY passing a description hash (without preimage),

Didn't follow here. The description hash is not related to the preimage.

**Comment by JssDWt** [comment]
> Didn't follow here. The description hash is not related to the preimage.

I meant the preimage to the description hash. So the description itself.

> Right but this can easily be solved by moving to the cln gRpc which exposes this. We already moved to cln gRpc in other endpoints.

That's all we need then!

**Comment by callebtc** [comment]
> CLN also doesn't support ONLY passing a description hash (without preimage), so probably the `deschashonly` flag while passing the entire description to CLN will do the trick for lnurl.

correct
