### ISSUE TITLE
trying to compile for python

### ISSUE THREAD

**Issue by massmux** [breez/breez-sdk#410]
When i go to run make python-linux, after some processing i get the following fatal error and i cannot figure out how to solve. 

error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/massmux/PycharmProjects/breez-sdk/libs/target/release/build/ring-68582ea93b0d7ad1/build-script-build` (exit status: 101)
  --- stdout
  OPT_LEVEL = Some("z")
  TARGET = Some("aarch64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_aarch64-unknown-linux-gnu
  CC_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_aarch64_unknown_linux_gnu
  CC_aarch64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  RUSTC_LINKER = None
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-linux-gnu
  CFLAGS_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_linux_gnu
  CFLAGS_aarch64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("neon")

  --- stderr
  running "aarch64-linux-gnu-gcc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/massmux/PycharmProjects/breez-sdk/libs/target/aarch64-unknown-linux-gnu/release/build/ring-a6ae36ef20f137b1/out/aesv8-armx-linux64.o" "/home/massmux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/pregenerated/aesv8-armx-linux64.S"
  thread 'main' panicked at 'failed to execute ["aarch64-linux-gnu-gcc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/massmux/PycharmProjects/breez-sdk/libs/target/aarch64-unknown-linux-gnu/release/build/ring-a6ae36ef20f137b1/out/aesv8-armx-linux64.o" "/home/massmux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/pregenerated/aesv8-armx-linux64.S"]: No such file or directory (os error 2)', /home/massmux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:653:9

**Comment by JssDWt** [comment]
@massmux Try passing your host target as an environment variable:
```
TARGET=x86_64-unknown-linux-gnu make python-linux
```

**Comment by massmux** [comment]
thank you. this made a step ahead, but still problems, it seems something else is missing?

157.2    Compiling vls-protocol v0.9.1-rc.2 (https://gitlab.com/cdecker/vls?tag=snapshot-20230620#3a016a06)
157.3 error: failed to run custom build command for `cln-grpc v0.1.3 (https://github.com/ElementsProject/lightning.git?branch=master#2d537076)`
157.3 
157.3 Caused by:
157.3   process didn't exit successfully: `/opt/breez-sdk/libs/target/release/build/cln-grpc-c852fdeb81d22f26/build-script-build` (exit status: 101)
157.3   --- stdout
157.3   cargo:rerun-if-changed=proto/node.proto
157.3   cargo:rerun-if-changed=proto
157.3 
157.3   --- stderr
157.3   thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
157.3       this knowledge. If `protoc` is installed and this crate had trouble finding
157.3       it, you can set the `PROTOC` environment variable with the specific path to your
157.3       installed `protoc` binary.If you're on debian, try `apt-get install protobuf-compiler` or download it from https://github.com/protocolbuffers/protobuf/releases
157.3 
157.3   For more information: https://docs.rs/prost-build/#sourcing-protoc
157.3   ', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/prost-build-0.11.9/src/lib.rs:1457:10
157.3   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
157.3 warning: build failed, waiting for other jobs to finish...
207.1 make: *** [makefile:66: python-linux] Error 101

**Comment by massmux** [comment]
thank you. finally resolved. i got a docker container of 11GB for getting the working library!
