### ISSUE TITLE
Inconsistent Invoice Payment Confirmation in sendPayment Method

### ISSUE THREAD

**Issue by aniketambore** [breez/breez-sdk#414]
In the `sdk-flutter` project, there seems to be an issue with the `sendPayment` method in the `BreezBridge`. 

**Expected Behavior:**
When attempting to pay an invoice for the first time, it should succeed, and subsequent attempts to pay the same invoice should result in a clear "Invoice Already Paid" exception.

**Actual Behavior:**
Currently, when paying an invoice for the second time or any subsequent attempts, the system still provides a success message. This is not the expected behavior and can be confusing to users.

**Steps to Reproduce:**
1. Create an invoice.
2. Attempt to pay the invoice for the first time (expect success).
3. Attempt to pay the same invoice again (expect an "Invoice Already Paid" exception).

**Additional Information:**
This bug affects the user experience, as users may believe they successfully paid the invoice multiple times when it should be prevented after the first payment. This issue should be addressed to ensure accurate feedback to users and proper handling of payment attempts.

**Comment by roeierez** [comment]
Seems like this is the implementation in greenlight/cln.  @ok300 I think we can mitigate that meanwhile with a simple/fast query to the db for that completed payment by hash.
