### ISSUE TITLE
Expose Channel Information

### ISSUE THREAD

**Issue by dleutenegger** [breez/breez-sdk#421]
We display our user debug information about his node, such as already exposed info like:
- max_receivable_msat
- max_payable_msat
- channels_balance_msat

But would also like to show more information about his individual channels. We are currently interested in the `num_inactive_channels`, `num_active_channels` & `num_pending_channels` which isn't exposed by the Breez SDK.

Thus, we are suggesting to create separate function that exposes detailed information about the nodes channels.

**Comment by kingonly** [comment]
Why this is needed in the UX? What if we add this info to the logs? Reason I'm asking is because there's a tradeoff between simplicity and verbosity.

**Comment by dleutenegger** [comment]
Yes, adding this information to the logs would be sufficient for our debugging purposes.

**Comment by kingonly** [comment]
@roeierez let's discuss

**Comment by roeierez** [comment]
@dleutenegger if this is for debugging/support of users then you can use the `execute_dev_command` that we expose on the sdk instance: https://github.com/breez/breez-sdk/blob/main/libs/sdk-core/src/breez_services.rs#L673
It is just a simple way to proxy some commands directly to the node and get the response as json string. We use it exactly for your use case and expose some "low level" commands that we think are useful without adding them to the main services interface.
For your specific request you can pass in "listpeers" which will give you all connected peers and channels.
See here for a list of commands you can use: https://github.com/breez/breez-sdk/blob/main/libs/sdk-core/src/greenlight/node_api.rs#L751

Does it meet your requirements?

**Comment by dleutenegger** [comment]
@roeierez Thanks, this should be enough. 

But looking at the CLN Docs for the [listpeers](https://docs.corelightning.org/reference/lightning-listpeers) command the channel information field is deprecated (removal in v23.11), so we would probably need the dev command `listchannels`.

**Comment by roeierez** [comment]
We added listpeerchannels as a dev command. In contrary to listchannels that shows all channels in the network this one shows only the channels connected to the user node which is, according to my understanding, your need.
Feel free to reopen this if anything else is needed here.
