### ISSUE TITLE
Feature request: return payment hash on a successful LNURL withdrawal

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#427]
It would be useful if `LnUrlCallbackStatus::Ok` included the payment hash of the invoice sent to the LNURL-w service. Otherwise, unless I'm missing something, it's hard for a consumer of the SDK to know exactly which payment is associated with this withdrawal.

**Comment by roeierez** [comment]
Sounds like a valid use case to me. cc @ok300
