### ISSUE TITLE
Disconnect function not working

### ISSUE THREAD

**Issue by kumulynja** [breez/breez-sdk#439]
**Environment**

- Flutter app with breez-sdk-flutter
- Android emulator

**What**
After a successful `initialize` and `connect`, calling `disconnect` throws the following error:

> Background processing is not running

**Comment by ok300** [comment]
@kumulynja thanks for the report!

@roeierez first I thought it's related to the signer starting asynchronously on `connect`, but looks like its flutter-specific.
