### ISSUE TITLE
Feature request: get info about failed payments

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#446]
It would be useful if `list_payments()` returned not only successful and pending payments, but also failed outgoing ones, ideally coupled with the reason they failed (e.g. `NO_ROUTE_FOUND`, `ALL_ROUTES_TRIED`, `TIMEOUT`). Filtering could be implemented to keep the current behavior in case someone isn't interested in this information.

**Comment by danielgranhao** [comment]
For consistency, the method `payment_by_hash()` could have the same behavior

**Comment by roeierez** [comment]
What is the use case you are looking for? Is it for show ing these to the user as part of the payments list? Or for some other purpose?

**Comment by danielgranhao** [comment]
Yes, for showing in the payments list

**Comment by roeierez** [comment]
> For consistency, the method `payment_by_hash()` could have the same behavior
Isn't it a bit different? I mean for a successful/pending payment this method can only return one result while it seems there could be several failed attempts (payments) for the same hash.

**Comment by danielgranhao** [comment]
I see what you mean, it depends on the model. New payment attempts could "overwrite" previous failed ones, in which case, `payment_by_hash()` could also return a failed payment attempt. If the data model allows for multiple failed attempts to pay the same invoice, then yes, it doesn't make sense to change `payment_by_hash()`. The latter shows a more complete picture, at the cost of cluttering the payment list.

**Comment by roeierez** [comment]
I would go for the simple approach as long as it meets the requirement. 
Only one payment in the database per hash which means an existing hash can be associated with either failed payment or successful one.
We override old payments with new payments of the same hash (so an old failed payment may be switched to a successful one after retrying to pay). Returning a failed payment from `payment_by_hash` then make sense.
What do you think @danielgranhao  ? Does it meet your requirements?

**Comment by danielgranhao** [comment]
@roeierez Agreed! Yes, that would meet our requirements 🙂
