### ISSUE TITLE
Bug: wildcard import of LDK crates leads to several compilation errors

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#447]
The `breez-sdk-core` crate depends on 2 LDK crates using a wildcard for the version. This leads to issues because the latest version of LDK introduced some API changes. We can fix this of course by pinning the LDK version to a compatible one, but it would make sense for the SDK itself to restrict its dependencies to compatible versions.

Example:
```
error[E0432]: unresolved imports `lightning_invoice::RawInvoice`, `lightning_invoice::SignedRawInvoice`
  --> /sdk-core/src/greenlight/node_api.rs:27:25
   |
27 | use lightning_invoice::{RawInvoice, SignedRawInvoice};
   |                         ^^^^^^^^^^  ^^^^^^^^^^^^^^^^ no `SignedRawInvoice` in the root
   |                         |
   |                         no `RawInvoice` in the root


```

**Comment by ok300** [comment]
Thanks for the report!

We'll move to explicit versioning, which should avoid this in the future.

**Comment by ok300** [comment]
Fixed, PR is merged.
