### ISSUE TITLE
Feature request: increase specificity of errors

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#459]
To be possible to create translatable, user-oriented error messages, the SDK would need to return more specific errors.

Example: when paying a Bolt11 invoice using `send_payment()`, several things can go wrong such as:
* invoice was already paid
* invoice was issued by ourselves
* invoice expired
* invoice from different network (e.g. testnet)
* not a single route found
* all routes tried
* timeout
* etc

If it could make sense to provide information to the user about a specific failure reason, then there needs to be a specific error variant to represent it, as describing the error in a string will only be useful to developers integrating the SDK.

Of the previous error examples, some could be argued if it makes sense to inform the user or not (not a single route found vs all routes tried vs timeout), but others, I think it definitely makes sense to inform the user about (e.g. invoice already paid, self-payment, invoice expired).

I expanded on the invoice paying example, but it most likely applies in other places. In general, any error that the user could be interested in or could react to, there should be a error variant for it, and a different error message returned by the SDK isn't enough.

With more specific errors, we can even give our users some advice; for example, check your internet connection, check that the recipient is connected to LN and online, LSP is down, etc...

**Comment by kingonly** [comment]
We give specific error to the best of what's possible in Lightning. Not sure what's missing exactly...

**Comment by roeierez** [comment]
@danielgranhao that makes sense. We will add more specific errors but this will be an on-going effort.
We will start with the `send_payment` and keep moving driven by your need/request.

**Comment by danielgranhao** [comment]
@kingonly Maybe I didn't explain it well enough. The problem isn't that the SDK isn't specifying the errors in any way; it's that it doesn't specify them in a way that we can handle programmatically.

Take this example: if a user tries to pay the same invoice twice, there's no good way for an app integrating the SDK to tell the user about it. Of course we get `SdkError::SendPaymentFailed { err: "Invoice already paid"}` but we would need something like `SdkError::SendPaymentFailed { code: SendPaymentCode::InvoiceAlreadyPaid, msg: "Invoice already paid"}`.

**Comment by danielgranhao** [comment]
@roeierez Thanks!

**Comment by kingonly** [comment]
Gotcha, makes sense

**Comment by JssDWt** [comment]
Posting this reference here. Next to the `code`, let's also add a `type` field to the errors to make javascript-like languages happy.
https://github.com/breez/breez-sdk/pull/298#issuecomment-1635619920

**Comment by roeierez** [comment]
> Posting this reference here. Next to the `code`, let's also add a `type` field to the errors to make javascript-like languages happy. [#298 (comment)](https://github.com/breez/breez-sdk/pull/298#issuecomment-1635619920)

Gladly uniffi added the ability to add fields to an error type (https://mozilla.github.io/uniffi-rs/udl/errors.html). I remember looking at this in the past and I think it was not possible so this design is certainly possible.
@danielgranhao What do you think as a rust user?

**Comment by danielgranhao** [comment]
@roeierez SGTM
