### ISSUE TITLE
Feature request: add `Network` field to `LNInvoice` 

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#462]
At the moment, `parse()` returns successfully when decoding a testnet Bolt11 invoice, and there's no way for the consumer of the SDK to learn the network of an invoice before calling `send_payment()` without parsing the invoice using alternative means.

Having the network field would allow us to check it and warn the user the invoice is "invalid" due to a mismatch in networks even before he tries to pay.

**Comment by ok300** [comment]
Would it work if we added an error type `SdkError::InvalidNetwork`? It could happen in other calls as well, not just `send_payment()`, and it would spare you all the extra checks.

**Comment by danielgranhao** [comment]
@ok300 Yes, that probably makes more sense. Thanks!
