### ISSUE TITLE
`listPayments` returns "paymentType": null

### ISSUE THREAD

**Issue by simongltr** [breez/breez-sdk#485]
I use RN on SDK version 0.2.3.

I started with a fresh wallet and used a swap + JIT channel opening to receive the funds.

Calling `listPayments` returns `"paymentType": null`. I saw on telegram that someone is getting the same from `send_payment`

The idea is to attach the correct tag to the tx history for easy readability.

Thank you,
Simon

**Comment by dangeross** [comment]
Thanks for the report @simongltr. Looks like there's missing a mapping of the payment type enum to string here. From future releases all RN code is now generated, so this should be solved in the next release.

https://github.com/breez/breez-sdk/blob/8637341e12efc1bf8d20793c123007a4844262f2/libs/sdk-react-native/ios/BreezSDKMapper.swift#L583-L594

**Comment by dangeross** [comment]
Fixed by #429

**Comment by griffinshuth** [comment]
So im actually using the new version and the BreezSDKMapper.swift is throwing errors for instance here is one of the errors

Value of type 'ClosedChannelPaymentDetails' has no member 'closingTxid'
![Screenshot 2023-10-16 at 3 34 13 PM](https://github.com/breez/breez-sdk/assets/41766864/2deb768f-81f7-4389-8cb3-b1734c317815)

**Comment by dangeross** [comment]
Hi @griffinshuth. Are you using release or buildin lhmug from the main branch?

**Comment by roeierez** [comment]
This is the latest version: https://www.npmjs.com/package/@breeztech/react-native-breez-sdk/v/0.2.5

**Comment by dangeross** [comment]
From the errors it looks like the main branch is being used against the release 0.2.5 cocoapods/maven libraries.

@griffinshuth can you change the example/package.json dependency to the following and reinstall:
```
"@breeztech/react-native-breez-sdk": "0.2.5",
```

@roeierez I think we should do this by default, set the dependency in the example app to the latest release, else as development happens on main the generated code and release libraries become inconsistent.
