### ISSUE TITLE
sendOnchain crash on iOS using RN SDK

### ISSUE THREAD

**Issue by damiandizeo** [breez/breez-sdk#487]
I use RN on SDK version 0.2.3.

when sendOnchain is called from JS, it crashes.

`@objc(sendOnchain:onchainRecipientAddress:pairHash:satPerVbyte:resolver:rejecter:)`
`func sendOnchain(_ amountSat:UInt64, onchainRecipientAddress:String, pairHash:String, satPerVbyte:UInt64, resolve: @escaping RCTPromiseResolveBlock, rejecter reject: @escaping RCTPromiseRejectBlock) -> Void {`

**resolver: (RCTPromiseResolveBlock)resolve** is missing here 

`RCT_EXTERN_METHOD(
    sendOnchain: (NSUInteger*)amountSat
    onchainRecipientAddress: (NSString*)onchainRecipientAddress
    pairHash: (NSString*)pairHash
    satPerVbyte: (NSUInteger*)satPerVbyte
    rejecter: (RCTPromiseRejectBlock)reject
)`

Thank you, Damian.

**Comment by dangeross** [comment]
Thanks for the issue @damiandizeo. I see the problem in reviewing the 0.2.3 release code. This is already resolved in the main branch and will be fixed in the next release.

**Comment by dangeross** [comment]
Fixed by #429
