### ISSUE TITLE
error running multiple users on the same instance (python)

### ISSUE THREAD

**Issue by massmux** [breez/breez-sdk#495]
i am trying to run multiple users in the same instance. this is the case of a backend managing multiple users. i am getting an error (ad described below) after discussing with the team, they gave me this example

https://gist.github.com/dangeross/b1c9a108852aa218b7b8a2e8848aed10

that is quite the same as i did. I tested that example, and get the same error

python3 test.py 
NodeState(id=XXX, block_height=810171, channels_balance_msat=2841488, onchain_balance_msat=0, utxos=[], max_payable_msat=2841488, max_receivable_msat=3997158512, max_single_payment_amount_msat=4294967000, max_chan_reserve_msats=0, connected_peers=['XXX'], inbound_liquidity_msats=97914512)
Traceback (most recent call last):
  File "/opt/breezerbot/test.py", line 50, in <module>
    multi_sdk_test()
  File "/opt/breezerbot/test.py", line 41, in multi_sdk_test
    sdk_2 = get_sdk(breez_sdk_api_key,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/breezerbot/test.py", line 26, in get_sdk
    sdk_services = breez_sdk.connect(config, seed, SDKListener())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/breezerbot/breez_sdk.py", line 5059, in connect
    return FfiConverterTypeBlockingBreezServices.lift(rust_call_with_error(FfiConverterTypeSdkError,_UniFFILib.breez_sdk_715c_connect,
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/breezerbot/breez_sdk.py", line 271, in rust_call_with_error
    raise error_ffi_converter.lift(call_status.error_buf)
breez_sdk.UniFFIExceptionTmpNamespace.InitFailed: SdkError.InitFailed('Failed to initialize the SDK: Failed to set global logger: attempted to set a logger after the logging system was already initialized')

**Comment by roeierez** [comment]
Thank you!
The only point in code this exception is thrown is here: https://github.com/breez/breez-sdk/blob/main/libs/sdk-core/src/breez_services.rs#L1169

And this function is not called within the sdk as it is mean for rust users only.
I really suspect the binaries are used in this example are old (maybe the build on top of main branch failed and you are mistakenly using old binaries?).
We did have this issue in the past, this is why I am suggesting to check the binaries.

**Comment by massmux** [comment]
i made the python binding from the github main. as below. is there a better way?


FROM rust:1.72.0

RUN apt-get update
RUN apt-get install -y protobuf-compiler
RUN cd /opt/ && git clone https://github.com/breez/breez-sdk.git


WORKDIR /opt/breez-sdk/libs/sdk-bindings


ENV TARGET=x86_64-unknown-linux-gnu
RUN make init
RUN make python-linux

[...]

**Comment by JssDWt** [comment]
@massmux Can you try building the docker image with the `--no-cache` option?

**Comment by massmux** [comment]
This issue actually seems resolved in the latest version of the library.
Thank you
