### ISSUE TITLE
Simplify getting preimage from `send_payment` result

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk#506]
To get to the preimage from the `payment` result of `send_payment`, the caller has to match the type of `payment.details` because the `PaymentDetails` are an enum:

```rust
pub enum PaymentDetails {
    Ln {
        #[serde(flatten)]
        data: LnPaymentDetails,
    },
    ClosedChannel {
        #[serde(flatten)]
        data: ClosedChannelPaymentDetails,
    },
}
```

However we know this could only have been a `LnPaymentDetails`.

We should simplify this.

Maybe construct a user-facing struct `LnPayment`, that is identical to `Payment` except it maps the details to `LnPaymentDetails`?

**Comment by JssDWt** [comment]
There is already an issue for this here https://github.com/breez/breez-sdk/issues/302

**Comment by ok300** [comment]
Duplicate of #302
