### ISSUE TITLE
Expose txid in ReverseSwapInfo

### ISSUE THREAD

**Issue by ubbabeck** [breez/breez-sdk#512]
It would be nice to be able to be able to retrieve either both the lockup txid and claimtx or  alternatively we return a generic one which shows the current txid.

Not sure what makes more sense to do.

**Comment by ok300** [comment]
I see a few options we can do this via new fields to `ReverseSwapInfo`:

1. expose one txid
  a. mandatory field, contains lockup or claim txid
  b. optional field, contains claim txid when available
2. expose both: mandatory lock txid, optional claim txid

Intuitively, 1b looks like the most useful for a user-facing app.

@ubbabeck @roeierez what do you think?

**Comment by roeierez** [comment]
The user is only interested in the final (claim) tx id,  I think this is the only tx we should associate with the swap. The rest is implementation details that are not interesting for the user.

**Comment by ubbabeck** [comment]
Agree with Roei, an optional field with the claimtxid as suggested in 1.b sounds good.

**Comment by ok300** [comment]
@roeierez just to doublecheck, this should go into `sync.reverse_swaps` correct?

**Comment by ubbabeck** [comment]
In breezmobile we display the lockup transaction and let the user know that we're awaiting the lockup transaction to be confirmed before sending the funds to the specified address. For people with knowledge about how reverse swap works this gives them transparency current state of the transaction, but for most users it might cause some confusion by displaying the lockup transaction. Ref breezmobile https://github.com/breez/breezmobile/pull/995

**Comment by roeierez** [comment]
@kingonly what do you think? Should we expose the lockup tx?

**Comment by kingonly** [comment]
@roeierez yes, we should. We added that to Breez mobile and it REALLY helped with the UX.

**Comment by roeierez** [comment]
Alright then @ok300 let's add it to the sdk info as well.
