### ISSUE TITLE
lnurl_withdraw should take an msat amount as parameter.

### ISSUE THREAD

**Issue by JssDWt** [breez/breez-sdk#514]
`min_withdrawable` and `max_withdrawable` are msat amounts, but `lnurl_withdraw` takes a sat amount. This is confusing. Dividing by 1000 may not always work if the amount is not a round sat amount.

Also it's not documented correctly: https://sdk-doc.breez.technology/guide/lnurl_withdraw.html

**Comment by ok300** [comment]
Related: #417

**Comment by JssDWt** [comment]
Fixed in https://github.com/breez/breez-sdk/pull/535
