### ISSUE TITLE
Extend `BreezEvent` with swap status changes

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk#518]
It can include swap and reverse swap state changes.

Suggested here: https://github.com/breez/breez-sdk/pull/515#pullrequestreview-1673879042

Includes doc updates:
- [ ] Send onchain snippet for checking status
- [ ] Receive onchain snippet for checking status

**Comment by ok300** [comment]
Should a new `BreezEvent` be emitted for each change in the swap status? Or only for the main cases (success / failure)?

Possible states are:

https://github.com/breez/breez-sdk/blob/5adbfac3948352d8823453a75e196cedb7817638/libs/sdk-core/src/models.rs#L1005-L1015

https://github.com/breez/breez-sdk/blob/5adbfac3948352d8823453a75e196cedb7817638/libs/sdk-core/src/models.rs#L305-L324

**Comment by roeierez** [comment]
For swap-in I believe users are interested in the following statuses:

WAITING_CONFIRMATION - transaction that sends funds to the address entered the mempool
CONFIRMED - funds are confirmed, ready to redeemed and complete the swap
REDEEMED - funds were redeemed successfully and the swap has completed
REFUNDABLE - swap has expired with some confirmed address and user should execute the refund API
REFUNDED - swap refund was executed and confirmed

We can use the above values as enum variants for `SwapInfoChanged` event.
