### ISSUE TITLE
Default cltv delta for invoices should be 144 blocks

### ISSUE THREAD

**Issue by JssDWt** [breez/breez-sdk#523]
Currently we take the default cltv delta of the node to create invoices. Greenlight is actually increasing the default cltv delta to 144 blocks, but it could make sense to put this in the SDK as well, to avoid surprises.

Problem is there is too little time to react if a htlc is not fully settled yet, but the signer is offline. Currently the default cltv delta is 9 blocks.

**Comment by roeierez** [comment]
We control the cltv delta only in the case we open a channel. In this case we take it from the lsp information and add it in the routing hints.
I think this should be changed in the lsp info after greenlight changes it.

**Comment by JssDWt** [comment]
@roeierez  This CLTV expiry is the final cltv expiry, which is defined by the recipient. There's also a CLTV delta for the LSP, but adding to the CLTV expiry of the recipient 'bumps' every expiry in the route. The cltv delta of the LSP is already set in the hop hint.

**Comment by roeierez** [comment]
I see. Thanks for clarifying
