### ISSUE TITLE
Feature request: allow onchain fees to be known before committing to paying them

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#526]
When either using any of the following methods:
* `send_onchain()`
* `sweep()`
* `refund()`

it would improve UX if we could know the fees that will be paid.

This could be done by splitting the methods into preparation and execution steps, such that after preparing, one can decide whether to execute or not based on the fees.

**Comment by roeierez** [comment]
That's right @danielgranhao 
for sweep we are going to introduce prepareSweep: https://github.com/breez/breez-sdk/pull/294
For send_onchain we have https://github.com/breez/breez-sdk/blob/main/libs/sdk-core/src/breez_services.rs#L630C18-L630C41
for refund perhaps we can add the refund tx weight to the `list_refundables` ?

**Comment by danielgranhao** [comment]
> That's right @danielgranhao
for sweep we are going to introduce prepareSweep: https://github.com/breez/breez-sdk/pull/294
For send_onchain we have https://github.com/breez/breez-sdk/blob/main/libs/sdk-core/src/breez_services.rs#L630C18-L630C41

Oh, sorry, completely missed that PR and the `fetch_reverse_swap_fees()` method. 

> for refund perhaps we can add the refund tx weight to the list_refundables ?

That would be nice!

**Comment by danielgranhao** [comment]
@roeierez I was working on a PR for adding the refund tx weight to `list_refundables` and realized that this won't lead to an exact prediction of the fees. Without knowing the address the user chooses, the tx weight will just be a guess (of course, very close to the real one, and one could opt for the worst-case scenario).

Wouldn't it be better to go with a "prepare" approach (similar to https://github.com/breez/breez-sdk/pull/294) that would provide the exact fee that will be used?

**Comment by JssDWt** [comment]
> For send_onchain we have https://github.com/breez/breez-sdk/blob/main/libs/sdk-core/src/breez_services.rs#L630C18-L630C41

Link currently points to a different line of code.

**Comment by roeierez** [comment]
Right @JssDWt I meant this one: https://github.com/breez/breez-sdk/blob/main/libs/sdk-core/src/breez_services.rs#L647

**Comment by JssDWt** [comment]
Permalinking that https://github.com/breez/breez-sdk/blob/3c602db1fb0799ad96922a618c6dbe180a722c5a/libs/sdk-core/src/breez_services.rs#L647

**Comment by danielgranhao** [comment]
Closed by #294 and #548
