### ISSUE TITLE
Bug: in-progress outgoing payment isn't included in payment list

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#570]
### Current behaviour

If `list_payments()` is called while `send_payment()` is running, the payment list doesn't include the new outgoing payment.

### Expected behaviour

If `list_payments()` is called while `send_payment()` is running, the payment list includes the new payment with status `PaymentStatus::Pending`

**Comment by danielgranhao** [comment]
Taking this up if no one has yet

**Comment by roeierez** [comment]
Its yours!

**Comment by danielgranhao** [comment]
I realized that calling `sync()` between the start of the payment and getting the payments list effectively circumvents the issue. I assume that syncing within the implementation of `list_payments` isn't a desirable fix as it makes the method rely on network requests, which up until now it doesn't. Am I correct in this assumption?

**Comment by roeierez** [comment]
Yes, correct.

**Comment by roeierez** [comment]
Can we close this @danielgranhao @dleutenegger  ?

**Comment by ok300** [comment]
Closing as per confirmation above.
