### ISSUE TITLE
Bug: pending outgoing payment of open bolt11 invoice returns amount inferior to the one attempted to be sent

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#599]
We've already experienced more than once that when paying an open (aka zero-amount) bolt11 invoice, if it stays pending, the `amount_msat` returned in `Payment` doesn't correspond to the amount that was attempted to be paid. 

In one instance, the payment was for 50k sats, and the `Payment` specified ~48323 sats, and in another, it was for 45k sats, and we got ~3631 sats. Looking at the logs, for the latter, I could see that it was an MPP and one of the parts was of 3631 sats, suggesting this is related.

Not sure if this could also happen for non-open invoices, but we haven't experienced it.

**Comment by roeierez** [comment]
I think it is not specific to zero amount invoice. It happens because we show the paid amount given by greenlight which probably sums the htlcs that are in flight 
@kingonly what do you think? Should we change the displayed amount to the whole intended amount for sending payments instead of showing the in-flight amount?

**Comment by kingonly** [comment]
@roeierez yes. Users don't need to be aware of multi htlcs.

**Comment by dleutenegger** [comment]
Taking this up

**Comment by dleutenegger** [comment]
Looked into this, seems like we could reuse the approach from #589 and reuse the field `failed_amount_msat` (happy to get suggestions about a unified name) to persist the amount the user paid and retrieve this value for `Pending` payments. This is necessary to support open invoices. But also depends on #570 to persist local data about `Pending` outgoing payments.

WDYT?

**Comment by danielgranhao** [comment]
@dleutenegger 
> ... reuse the field failed_amount_msat (happy to get suggestions about a unified name) ...

What about `attempted_amount_msat`?

**Comment by dangeross** [comment]
> What about `attempted_amount_msat`?

I think `attempted_amount_msat` scans for both failed and pending payments 👍
