### ISSUE TITLE
Python Wheels for Python 3.11 and 3.12 are missing

### ISSUE THREAD

**Issue by prusnak** [breez/breez-sdk#606]
See https://pypi.org/project/breez-sdk-lib/#files

There are only wheels for Python 3.8, 3.9 and 3.10.

Please make wheels for Python 3.11 and 3.12 available too. Always make sure you submit wheels for all supported Python versions.

**Comment by prusnak** [comment]
ISTM all you need to change is this line:

https://github.com/breez/breez-sdk/blob/main/.github/workflows/publish-python.yml#L32

to read: `python: ["3.8", "3.9", "3.10", "3.11", "3.12"]` and re-run the build.

And then also changing the README.md here: https://github.com/breez/breez-sdk/blob/f5fac7e7713002df2b60532ba740776ec475ce3c/libs/sdk-bindings/bindings-python/README.md#L26

**Comment by cnixbtc** [comment]
Hey @prusnak, thanks for raising this. I'll get back to you on this tomorrow.

**Comment by cnixbtc** [comment]
@prusnak I've added 3.11. and 3.12 support to our release pipeline. Once merged, we'll create a new release on PyPi (likely 0.2.9.post1) which should then include wheels for those Python versions. I'll keep you posted here.

**Comment by cnixbtc** [comment]
Hey @prusnak we just published 0.2.9.post3 which includes wheels for Python 3.11 and 3.12. Please let me know if that solves your issue. You can install this version using:

``` python
pip install breez-sdk==0.2.9.post3
```

**Comment by prusnak** [comment]
Thanks. It works!
