### ISSUE TITLE
Bug: receiving payment that required a channel opening has `fee_msat` 0 

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#629]
We've noticed that sometimes, a receiving payment that required the opening of a new channel, when fetched using `list_payments`, has its `fee_msat` field set to 0. 

One of the nodes where we noticed this was created last week.

I haven't found a way to reproduce this reliably. Sometimes, it behaves as expected, and in other cases, it doesn't.

**Comment by roeierez** [comment]
@danielgranhao do you have a test node that this is reproduced there? If you are able to share the sqlite db with me it would be helpful to investigate that.

**Comment by danielgranhao** [comment]
@roeierez Yes, @dleutenegger will provide you with one.

**Comment by roeierez** [comment]
I still wasn't able to reproduce this.

**Comment by danielgranhao** [comment]
We haven't experienced it again as well. It might have been fixed. I'll mention it again if we see it.

**Comment by ok300** [comment]
Closing this, as it seems fixed. Please let us know if it happens again.
