### ISSUE TITLE
Bug: Failure to decrypt AES success action in payRequest should not fail the payment

### ISSUE THREAD

**Issue by andrei-21** [breez/breez-sdk#632]
### Problem description

If there is an AES success action in `payRequest` (LUD-10) then failure to decrypt `ciphertext` should not fail the payment, since the funds were actually sent.

### Current behavior
If Breez SDK fails to decrypt `ciphertext` with `payment_preimage` it returns `LnUrlPayError::AesDecryptionFailed`.

### Expected behavior

The SDK returns `Ok(LnUrlPayResult::EndpointSuccess)` with a value of `SuccessActionProcessed` indicating that it failed to decrypt the ciphertext with the error message.

**Comment by kingonly** [comment]
@andrei-21 which lnurl service reproduces this issue?

**Comment by kingonly** [comment]
@roeierez please advise. @andrei-21 feel free to offer a fix.

**Comment by roeierez** [comment]
@andrei-21 sure, your proposal looks good to me. Feel free to go ahead with that.

**Comment by ok300** [comment]
Fixed by #637.
