### ISSUE TITLE
Unable to receive payments if persisted LSP is removed from LSP list

### ISSUE THREAD

**Issue by dangeross** [breez/breez-sdk#634]
If there is an existing channel with an LSP (A), but the LSP list for an API key is updated to switch to LSP (B), the node cannot receive payments to LSP (A)'s channel because the LSP lookup of the node's persisted LSP (A) fails.

**Comment by roeierez** [comment]
@dangeross perhaps the root cause of the issue is that inside `connect_lsp_peer` we only choose lsp if the selected lsp is empty?
Perhaps we should also choose a new lsp if the current lsp is not in the list?

**Comment by dangeross** [comment]
I think it would make any existing channels to other LSPs unusable in receive_payment. 

If the amount_msat < inbound_liquidity_msats:
1. no new channel needed
2. no short_channel_id found for new LSP in peer channels (default to 1x0x0)
3. no lsp hint found in invoice for new LSP
4. add lsp hop with new LSP id & short_channel_id 1x0x0
5. no payment registered with LSP
6. payment tries to route through new LSP with no channel
