### ISSUE TITLE
Feature request: Allow SDK users to store additional metadata inside SDK storage

### ISSUE THREAD

**Issue by andrei-21** [breez/breez-sdk#635]
It would be useful for SDK users to be able to persist additional metadata inside the SDK storage.

Some metadata might be **associated with payments** (e.g. fiat exchange rate, timezone, user category).
Also it would be nice if:
* the SDK allows to search by such data using `list_payments()`
* SDK encrypts the data (since such data might be private)
* the SDK sync the data between different instances

Probably a solution might be a field allowing to store a JSON-like structure or multiple fields storing key-value pairs.

Another usecase is to persist data **not associated with a particular payment** like users settings (e.g. fiat currency, language).

**Comment by roeierez** [comment]
@andrei-21  Metadata associated with payments makes sense, how would be the ideal interface for that? Should we add the metadata parameter to all kind of send payment API methods (spontaneous, lnurl pay, pay bolt11 )?
Also do we wish to add metadata for receiving payments as well (withdraw_lnurl, receive_payment, swap)?
Other approach would be just add one method `set_payment_metadata(payment_hash, metadata)` and then the sdk handles the join of this data into the payment when the payment is requested.

**Comment by hydra-yse** [comment]
@andrei-21 I hope our solution satisfies the use cases you have requested. Just a couple of notes, which have also been documented:
- When filtering for payments, it is necessary to wrap strings in double-quotes when filtering for JSON strings, as currently we perform a one-to-one comparison
- When filtering specific arrays/objects, it is important to remove whitespaces/newlines in those fields, as those are counted too
