### ISSUE TITLE
Can't pay an invoice with an amount

### ISSUE THREAD

**Issue by bilthon** [breez/breez-sdk#641]
I'm updating my [CLI tool](https://github.com/tmrwapp/breez-sdk-cli-wallet) to the latest SDK version, commit e91348b and I am unable to pay an invoice with an amount. The [documentation](https://sdk-doc.breez.technology/guide/send_payment.html) states that the `amount_msat` is is optional and should only passed if the bolt11 doesn't specify an amount. And this works for invoices without amounts, but for invoices with a specified amount I'm getting this error:

```
SendPaymentRequest.__init__() missing 1 required positional argument: 'amount_msat'
```

If I do what the error says and add the `amount_msat` disregarding the documentation I get this other error:

```
SendPaymentError.InvalidAmount('Invalid amount: Amount should not be provided when paying a non zero invoice')
```

**Comment by JssDWt** [comment]
We're missing the default null value for that field. I'll make a pR for that.

In the meantime you can pass `None` as the second argument if the invoice has an amount.
