### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by yukibtc** [breez/breez-sdk#65]
Hey, I just fond this repo and I'm interested to contribute but greenlight repo is private. How can I start? Where can I ask for a ssh-key?

**Comment by cdecker** [comment]
Hi @yukibtc, I'm the lead the developer for Greenlight. We're not quite ready for publication just yet, but if you're ok with it we can set up a quick sync to see if we can give you access to the repo ahead of publication. Feel free to reach out to me at decker@blockstream.com
