### ISSUE TITLE
Feature request: Implement `mnemonic_from_seed` at top level

### ISSUE THREAD

**Issue by rustaceanrob** [breez/breez-sdk#696]
The `mnemonic_to_seed` is particularly useful but I would also make great use of the inverse function, `mnemonic_from_seed`, because I am storing and working with the resulting `Vec<u8>` (in Swift and Python bindings). If others would find this useful I can implement.

**Comment by ok300** [comment]
Thanks for reaching out!

It's not possible to get back to the mnemonic from the seed bytes. The seed is derived from the mnemonic using a one-way function similar to hashing. See steps 7-9: https://bitcoin.stackexchange.com/a/114346

**Comment by rustaceanrob** [comment]
Oops! I was thinking of the initial entropy. Thanks for clearing that up
