### ISSUE TITLE
private repo used in public code ! 

### ISSUE THREAD

**Issue by jawedsarwar** [breez/breez-sdk#70]
Hello @roeierez we are building the public (MIT) repo at https://github.com/breez/breez-sdk but this line is giving us error as we do not have access to this private repo - any thoughts on this? https://github.com/breez/breez-sdk/blob/f4be15cdd2e76c53846fa3e453cca591426ecd28/libs/sdk-core/Cargo.toml#L19

**Comment by cdecker** [comment]
That code is part of the Greenlight repository that will eventually be open-sourced (also as with an MIT license), but we are not quite ready to do so at this time. I'm more than happy to give you access ahead of time, but we want to prevent exposing users to the quickly evolving state of the repo.

Feel free to contact me at decker@blockstream.com if you're interested :-)
