### ISSUE TITLE
Export EvenType enum from breez-sdk-react-native

### ISSUE THREAD

**Issue by 2624789** [breez/breez-sdk#700]
In a previous version this type was exported:

https://github.com/breez/breez-sdk-react-native/blob/2fb14f566eedbf6fad26368a945ff75616f467e3/src/index.tsx#L27

It is not exported now in [libs/sdk-react-native/src/index.ts.](https://github.com/breez/breez-sdk/blob/300546a4b456c968a6f0d92c772a44385752aeb5/libs/sdk-react-native/src/index.ts)

Is there a reason for not exporting it? Could it be exported again?

It is useful when handling events on the front

**Comment by dangeross** [comment]
Hi @2624789, it's called BreezEventVariant now:
https://github.com/breez/breez-sdk/blob/300546a4b456c968a6f0d92c772a44385752aeb5/libs/sdk-react-native/src/index.ts#L531-L540
