### ISSUE TITLE
Override working_dir (for local static backup data)?

### ISSUE THREAD

**Issue by prusnak** [breez/breez-sdk#701]
PR https://github.com/breez/breez-sdk/pull/448 introduced local copy of static backup data, where 2 SQLite files are stored in the working_dir.

Is there a way how to configure the location (for example from Python).

This is causing issues with LNbits, where I want to be able to configure the location of the working dir (to be `./data/breez` for example).

**Comment by kingonly** [comment]
Do you mean you want to set the working_dir?
See: https://sdk-doc.breez.technology/guide/getting_started.html

**Comment by prusnak** [comment]
> See: https://sdk-doc.breez.technology/guide/getting_started.html

Yes, that was it. Thanks for the guidance!
