### ISSUE TITLE
Feature Request: Explicit list_channel_history

### ISSUE THREAD

**Issue by alexlwn123** [breez/breez-sdk#702]
If a user wants to calculate the fees they've paid to an LSP, there currently isn't a great way to do so. 

They could use `list_payments` and filter payments where the `amount_msat` is significantly lower than the amount encoded within the `bolt11` invoice... but this doesn't seem like a good solution.

I think it'd be helpful to:  
1. Add field(s) to `list_payments` to distinguish if a payment was involved in a JIT channel creation and include the fee paid to the LSP. (perhaps by specifying `requested_amount`, `lsp_fee`, and/or `received_amount`)
2. Add another call to only show those payments (e.g. `list_channel_history`).

**Comment by roeierez** [comment]
Thanks @alexlwn123 for opening this.
Sounds reasonable to me. Instead of adding another endpoint that filters payment that were used to open a channel we can add another enum variant to the list_oayments filter.
