### ISSUE TITLE
Add the payer invoice to the payment in case of JIT channel

### ISSUE THREAD

**Issue by roeierez** [breez/breez-sdk#703]
This was requested by @andrei-21 in telegram.
It seems that it will also solve https://github.com/breez/breez-sdk/issues/702

**Comment by hydra-yse** [comment]
If my understanding is correct, the invoice should already be present inside the `PaymentDetails`, right? So when a Payment is related to a transaction (not closed channel), you should be able to retrieve it: https://github.com/breez/breez-sdk/blob/82e30c4e9c898748131fc434fc832b010f3b74d0/libs/sdk-core/src/models.rs#L714-L720

**Comment by JssDWt** [comment]
> If my understanding is correct, the invoice should already be present inside the `PaymentDetails`, right? So when a Payment is related to a transaction (not closed channel), you should be able to retrieve it:

The invoice shown there is a different invoice than we sent to the payer. Because the recipient receives a smaller amount than the sender sent in case of a jit channel. So we store a smaller invoice on the node, and modify the invoice to the actual amount to send to the sender.

**Comment by hydra-yse** [comment]
Thanks @JssDWt , I understand now. Storing the actual invoice sent to the payer though does seem to require changes to the lsp's reply, as currently it is just an empty object:
https://github.com/breez/breez-sdk/blob/c60b12264e7f9103283c8fa4c57e2c3423faaeec/libs/sdk-core/src/grpc/proto/breez.proto#L176
Thinking on it again, maybe this is not necessary for now. As pointed out in PR https://github.com/breez/breez-sdk/pull/758, maybe just checking if `payer_amount_msat` is not null would be enough to satisfy #702's requirements, without needing any further changes to the LSP. @roeierez Let me know what you think.
