### ISSUE TITLE
Allow set close_to address

### ISSUE THREAD

**Issue by roeierez** [breez/breez-sdk#711]
This address is the channel closure address where the funds are swept to.
GL supports this: https://github.com/Blockstream/greenlight/blob/6ab8f3205639ddf611f99e71691f7515fc0d24e6/libs/proto/greenlight.proto#L55C16-L55C24

**Comment by JssDWt** [comment]
I think the close_to address is only used on mutual close. It should still be useful to set, but just noting it's not a silver bullet for all your onchain funds.

**Comment by roeierez** [comment]
I agree adding a method seems like most fit here.
Using the config is a problem since it can only be used when the sdk connects.
Although perhaps we can mimic GL here and add a method setNodeConfig? Or you think it is going to be confusing with the current config? Just looking for a way not to add methods when gl adds more parameters to their node config.

**Comment by dangeross** [comment]
I might work `set_node_config(NodeConfigRequest req)`. But maybe it might be confusing as there is already a NodeConfig for passing the node credentials.
