### ISSUE TITLE
Swift Initialization DB Error

### ISSUE THREAD

**Issue by rustaceanrob** [breez/breez-sdk#713]
I am getting an error: `Fatal error: 'try!' expression unexpectedly raised an error: BreezSDK.SdkError.Generic(message: "Generic: SQL: unable to open database file: ./storage.sql")
2024-01-08 11:18:53.` when initializing the SDK in my Swift app. Should the case when there is no DB present in the working directory be handled differently? I can make a `storage.sql` in my project, or use a different config option, but maybe the error should be handled in the background for the SDK user? 

My function: 

```swift
func startServices(mnemonic: String) throws {
        let seed = try? mnemonicToSeed(phrase: mnemonic)
        let config = getConfig()
        self.sdk = try! connect(config: config, seed: seed!, listener: SDKListener())
}
```

**Comment by dangeross** [comment]
Is `./storage.sql` writable by your application? The SDK will create the .sql files in the working directory as long as it is writable. You can set the working directory in the config using `config.workingDir`. In Swift you might want to use the applicationSupportDirectory as the workingDir, or create a directory off of the applicationSupportDirectory.

**Comment by rustaceanrob** [comment]
I assume the problem is `./storage.sql` is not writable then. I set the `config.workingDir` to `applicationSupportDirectory` and the SDK threw the same error. Apologies I'm new to Swift and will have to research some fixes

**Comment by dangeross** [comment]
No problem, here's how we generate the workingDir path in the Swift native part of React Native. Hope it helps
https://github.com/breez/breez-sdk/blob/main/libs/sdk-react-native/ios/RNBreezSDK.swift#L10-L19

**Comment by rustaceanrob** [comment]
The following worked: 

```swift
var breezSdkDirectory: URL {
        let applicationDirectory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let breezSdkDirectory = applicationDirectory.appendingPathComponent("breezSdk", isDirectory: true)

        if !FileManager.default.fileExists(atPath: breezSdkDirectory.path) {
            try! FileManager.default.createDirectory(atPath: breezSdkDirectory.path, withIntermediateDirectories: true)
        }
        return breezSdkDirectory
    }
```

With an initialization via:

```swift
config.workingDir = breezSdkDirectory.absoluteString
```

Before we close, is this something that should go into the getting started docs?

**Comment by dangeross** [comment]
I see your point, although its application/platform specific. I'll add a developer note in the docs
