### ISSUE TITLE
Swap indefinitely pending, as long as initial tx is not confirmed

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk#726]
As long as the initial swap transaction remains unconfirmed, the SDK
- cannot refund the swap
- cannot complete the swap

This prevents the SDK from performing further swaps.

There is no perfect solution, because as long as the initial tx is in *some* mempools, it can end up being mined at some point in the future. Thus, the SDK has to be ready for that possibility, so it has to keep track of this pending swap.

Some possible solutions for the sender are:
- to bump the fees with RBF
- to use CPFP in order to get the swap tx to be mined sooner
- ... (TBD)

Posting this here to collect feedback and ideas.

**Comment by kingonly** [comment]
https://breez-tech.slack.com/archives/C06330E0S4X/p1705525064790539

**Comment by roeierez** [comment]
Following our discussion:
1. We need to consider swaps as redeemable as long as there are unpaid confirmed funds regardless of the mempool status.
2. We need to add API to rescan all swaps (not only those that are monitored).
