### ISSUE TITLE
Bug: `max_reverse_swap_amount()` returns 0 when balance is above 500k sats

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#739]
As the title describes, I'm getting `0` in response to calling `max_reverse_swap_amount()` even though my balance is above 500k sats, all in a single channel.

**Comment by roeierez** [comment]
@danielgranhao could you DM me your logs?

**Comment by roeierez** [comment]
@danielgranhao is this still happening? Do we have a reproducer?

**Comment by danielgranhao** [comment]
@roeierez We never saw it again. It it happens again, I'll reopen :)

**Comment by danielgranhao** [comment]
@roeierez On my side, it is working properly now. I'm just checking with others that they also stopped experiencing the issue. I will close the issue once I confirm.
