### ISSUE TITLE
Bug: `SwapInfo` includes msat amount in field named `paid_sats`

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#746]
As the title describes, I found that the swap info struct being returned from `list_payments` provides the paid msat amount instead of the sat amount. 

After a quick inspection of the source code, indeed, the msat amount is being persisted in the db into a column named `paid_sats`. 

It should be a trivial fix. It's just a matter of deciding if it makes sense to fix it by persisting the sat amount or changing the column name and variables to `paid_msats`.

**Comment by roeierez** [comment]
I leaning toward changing the column name since we have the lightning payment in msat?
