### ISSUE TITLE
`SwapInfo` field `created_at` is always zero

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk#774]
I don't know if this field is supposed to be a timestamp or a blockheight. While trying to figure that out from the source code, I realized this isn't ever modified from the initial moment a swap is created (`created_at` set to zero).

I also confirmed from a confirmed successful swap of mine that the value of `created_at` was indeed zero.

**Comment by roeierez** [comment]
Thanks @danielgranhao for bringing to our attention.
I actually look at the field and the comment looks wrong (Relative time lock start) The relative time lock starts at confirmation and not at creation so the creation time is not really needed IMO.
Let me know if I am missing something in my assumption.

**Comment by danielgranhao** [comment]
@roeierez Yes, it would make sense if the field was named `confirmed_at`.

**Comment by roeierez** [comment]
Alright then. Let's rename it to `confirmed_at` and use the block height of the confirmed transaction.
