### ISSUE TITLE
Include README & CHANGELOG when publishing Flutter plugin

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/breez-sdk#798]
Readme & changelogs appear to be outdated on https://pub.dev/packages/breez_sdk/changelog & [breez-sdk-flutter](https://github.com/breez/breez-sdk-flutter/blob/main/CHANGELOG.md).

Let's includes these files in the publishing process.

Note: Our README has instructions on how to build the SDK locally. I'd suggest creating a new `README.pub.md` file and use that on publishing process.

**Comment by erdemyerebasmaz** [comment]
Created a sample README that will be used on pub.dev here: 208722f5b5fa819b826a665e7b3ec5ff8cfe7fad

**Comment by cnixbtc** [comment]
Will add that. It's an easy fix. Let's maintain the changelog in the main repo (see https://github.com/breez/breez-sdk/pull/797) and then copy it over to here on publishing.
