### ISSUE TITLE
New "LnUrlPayWithZaps" type in the `InputType` enum

### ISSUE THREAD

**Issue by simongltr** [breez/breez-sdk#840]
Hey Breez team, we are in the process of implementing Zaps in our app.

The function `parse_input` of the sdk returns a `LnUrlPay` `InputType` which is normal. The issue is that the `nostrPubkey` and `allowsNostr` fields (from [NIP57](https://github.com/nostr-protocol/nips/blob/master/57.md)) are removed because not part of the [lud06](https://github.com/lnurl/luds/blob/luds/06.md) spec. 

To avoid workarounds like fetching 2 times the same thing (1 to retrieve nostr zaps data, 1 by the `parse_input` function), I feel like it would make sense to add a new "LnUrlPayWithZaps" type in the `InputType` enum. It would contain the data from `LnUrlPay` and the `nostrPubkey` and `allowsNostr` fields.

Any other equivalent improvement is welcome.

Thank you,
Simon

**Comment by JssDWt** [comment]
Other options could be
- adding `nostr_pubkey` and `allows_nostr` fields to the `LnUrlPayRequestData` struct
- adding a dictionary named `other` to the `LnUrlPayRequestData` struct, containing unknown fields

**Comment by simongltr** [comment]
I let you make the final choice, having access to `nostr_pubkey` and `allows_nostr` is enough for us right now.

With option 2 future protocols data will be accessible without any change to the SDK though

**Comment by roeierez** [comment]
@simongltr LNURLPay has a metadata field which arbitrary data can be encoded inside, did you consider making use of that? @JssDWt what do you think?

**Comment by JssDWt** [comment]
@roeierez It's a standard in NIP-57 https://github.com/nostr-protocol/nips/blob/master/57.md, it contains fields inside the lnurlp response. So these fields are not in the metadata. Standard lnurlp response looks like this:

```
{
    "callback": string, 
    "maxSendable": number, 
    "minSendable": number, `maxSendable`
    "metadata": string, 
    "tag": "payRequest"
}
```

Response with zaps support looks like this:

```
{
    "callback": string, 
    "maxSendable": number, 
    "minSendable": number, `maxSendable`
    "metadata": string, 
    "tag": "payRequest",
    "nostrPubkey": string,
    "allowsNostr": boolean
}
```

So it's not in the metadata field.
All major lnurl providers support this. If you get a random lnurlp response from Alby or Walletofsatoshi for example, the fields are there.
