### ISSUE TITLE
Update `max_allowed_deposit` on previously created swaps if possible

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/breez-sdk#871]
If any swap address we've created in the past hasn't been used, we return that same address when `create_swap_address` is called(through `receive_payment`). 

Due to this behavior, changes introduced in
- #861

only apply to newly created swap addresses.

If it's possible to retrieve `max_allowed_deposit` using SwapperAPI without creating a new swap, we should update `max_allowed_deposit` of the unused swap with the latest limits.

In theory, you should only have a single unused address at a time and calling a new API to fetch latest maximum values for swaps created before this transitory period is perhaps going a bit overboard as these limits rarely change afaik.

**Comment by roeierez** [comment]
I don't think we should do that @erdemyerebasmaz. We can't update these amounts whenever the balance changes.

**Comment by roeierez** [comment]
Perhaps the right thing is to save in the db the returned value from the swapper (4m sats) and on every return calculate based on the balance locally.

**Comment by erdemyerebasmaz** [comment]
> Perhaps the right thing is to save in the db the returned value from the swapper (4m sats) and on every return calculate based on the balance locally.

Yes, that's applicable for the case where value from the swapper stays the same and we should update maximum allowed deposit of unused swap each time we retrieve it.

The main issue exists for unused swaps that were created using the old( fund manager) client, where 900k sats is returned as the maximum depositable value but server side is actually enforcing 4M. Since we won't be able to create a new address while we have an unused swap, we won't be able to retrieve & save the new value(4M sats).

We've opened this issue to investigate if it's possible to retrieve maximum limit without creating a new swap.

**Comment by JssDWt** [comment]
> Perhaps the right thing is to save in the db the returned value from the swapper (4m sats) and on every return calculate based on the balance locally.

Thing is the server does the balance check itself for nodes connected to Breez LSP. So the balance _may_ already be deducted from the max_allowed_deposit we receive from the server.  That value is not useful anymore after some time. Say the server returns 2M max_allowed_deposit. We persist that. Then you send out all your balance. Then when you want to do the swap again, we calculate the max deposit amount based on min(max_from_server, max_receivable). This would return 2M, not 4M. 

Other options I see are:
- add an api to Breez server to request only the min and max deposit amounts for a given node
- only reuse unused swaps if they have been created 'recently', within a given time interval

**Comment by roeierez** [comment]
The server validation is for breez mobile users right? Not for the sdk users that are connected to the sdk lsp. I think this coupling is not good as we see that in reality the swapper doesn't have access to the user balance..
How about leave a client side logic and let the swapper return the absolute max swap amount?

**Comment by erdemyerebasmaz** [comment]
> The server validation is for breez mobile users right? Not for the sdk users that are connected to the sdk lsp. I think this coupling is not good as we see that in reality the swapper doesn't have access to the user balance.. How about leave a client side logic and let the swapper return the absolute max swap amount?

> Other options I see are:
> 
>   - add an api to Breez server to request only the min and max deposit amounts for a given node

We're interested in retrieving min/max absolutes from server, even if the node is connected to Breez LSP, and calculate `max_allowed_deposit` against current balance after retrieving unused swap from db on client side.
