### ISSUE TITLE
[Android] [react-native] - Error when initializing

### ISSUE THREAD

**Issue by Czino** [breez/breez-sdk#889]
Using react-native, there's an error immediately from the native code:

```
Invalid Structure Field in class g1.18, field name 'b' (class g1.k8$a): Can't create an instance of class g1.k8$a, requires a public no-arg constructor:
java.lang.reflect.InvocationTargetException
```

There's no error for iOS builds.

Package: `@breeztech/react-native-breez-sdk`
Version: `0.3.6`

react-native: `0.71.14`

**Comment by kingonly** [comment]
@dangeross please take a look when you can

**Comment by dangeross** [comment]
Hey @Czino, I assume you were integrating the SDK into your app before and that things were working normally? Did the error start occurring once you changed the SDK version or implemented specific functionality of the SDK? In TG you mentioned switching to certificates, could it be related to this?

**Comment by Czino** [comment]
Hi @dangeross,

no, it was the first time we built for Android and encountered this error. We are primarily developing on iOS and then test later on Android.

The error occurred with and without the use of the certificates.

I assume this error is generally present. IIRC it already occurs when calling `mnemonicToSeed`.

**Comment by dangeross** [comment]
@Czino I've not seen this error relating to the SDK before. It seems from the exception related to maybe deserializing data, perhaps there is some bad data or class object being sent over the bridge from javascript to the native component. Can you provide a code snippet here (or link if open source) where you think it's happening and I'll take a look

**Comment by Czino** [comment]
It's in this place: https://github.com/Peach2Peach/peach-app/blob/feature/liquid-integration/src/utils/lightning/initLightningWallet.ts#L34

**Comment by dangeross** [comment]
Checking the repo, it doesn't look like the [react-native-fs](https://github.com/itinance/react-native-fs) dependency is fully setup like in the documentation, specifically adding the:
- dependency to android/app/build.gradle
- registering the package in MainApplication
Check you check these just to rule react-native-fs out?

**Comment by dangeross** [comment]
@Czino did you manage to figure out the issue?

**Comment by dangeross** [comment]
@Czino please reopen if you continue to have issues
