### ISSUE TITLE
impossible connect to gl with breez-sdk-cli

### ISSUE THREAD

**Issue by vincenzopalazzo** [breez/breez-sdk#891]
I am testing breeze sdk with green and with the breez-sdk-cli and I am getting the same error that I am not able to fix.

----

The error is

```
dk> connect -c /home/vincent/Downloads/client-key.pem -k /home/vincent/Downloads/client.crt
Error: Generic: Generic: transport error
sdk> connect -k /home/vincent/Downloads/client-key.pem -c /home/vincent/Downloads/client.crt
Error: Generic: Generic: Generic: status: Internal, message: "protocol error: received message with invalid compression flag: 66 (valid flags are 0 and 1) while receiving response with status: 502 Bad Gateway", details: [], metadata: MetadataMap { headers: {"content-type": "text/plain; charset=utf-8", "content-length": "11", "date": "Sun, 24 Mar 2024 13:35:08 GMT"} }
sdk>
```

**Comment by cdecker** [comment]
Are you using Tonic with the compression feature? I know we have one place where we look into the payload, but that's in the approver in the signer, not in the client. Googling this myself I found a couple of people reporting this error or a similar one on `tonic`, so I'm tempted to mark this as an upstream issue. Could be a regression, so we could look through the previous versions of tonic to see if pinning might be a quick fix.

**Comment by cdecker** [comment]
The error originates here by the way:

https://github.com/hyperium/tonic/blob/eeb3268f71ae5d1107c937392389db63d8f721fb/tonic/src/codec/decode.rs#L165-L174

Quite far away from any code we touch ourselves as far as I know.

This is the only code that touches the payloads at the level that'd be required here:

https://github.com/Blockstream/greenlight/blob/08b2accdcb59f4412e2842313f534d21a14d3e64/libs/gl-client/src/node/service.rs#L108-L152

It essentially reads and buffers the request, so it can sign it, and then forwards it unmodified to the server. So it looks like either the server tonic library needs bumping, or the client has a regression and we need to pin it to an earlier version.

Interestingly, when I use `glcli` locally, which builds on top of `gl-client-py` and `gl-client` crate, so the same basis as Breez SDK, it works fine. That to me is an indication that it may be related to different versions of the `tonic` library getting pulled in.

**Comment by vincenzopalazzo** [comment]
idk if this can help but it is happening also from green point of view

![signal-2024-03-24-130718](https://github.com/breez/breez-sdk/assets/17150045/3ffd72b9-009d-4ab8-84fc-75dcc13de06c)


let me know if I can help in any way

**Comment by roeierez** [comment]
@cdecker the same client build worked yesterday. It indicates that it may not be something on the client. Unless this error is somehow not consistent.

**Comment by vincenzopalazzo** [comment]
>Unless this error is somehow not consistent.

it is on green

**Comment by roeierez** [comment]
@cdecker @vincenzopalazzo sorry, I just realized the LSP API returns this error. We are on it.

**Comment by roeierez** [comment]
Should be working now
