### ISSUE TITLE
Unable to parse upper case Bech32 bitcoin addresses

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/breez-sdk#894]
Encountered this issue when investigating:
- https://github.com/breez/c-breez/issues/844

QR code we create on "Receive via BTC Address" page on C-Breez is uppercase as per:

> Bech32 addresses consisting of uppercase and digits results in more compact QR codes.
> NB. If we ever generate BIP21 URI's that have query parameters, this will have to be fixed so that
> we will not change the case of the parameters because BIP21 parameters are case sensitive.
> Ref. https://bitcoinops.org/en/bech32-sending-support/#creating-more-efficient-qr-codes-with-bech32-addresses
>
> CC: @roeierez

and they failed to get parsed using `parseInput` API.

**Comment by roeierez** [comment]
@erdemyerebasmaz  I just use sdk.parse and passed the "received via btc address" output and it worked just fine.

**Comment by ok300** [comment]
After some talks with @erdemyerebasmaz , it turns out the problem is when the `BITCOIN:` prefix is in uppercase.

I added a fix in #896.

**Comment by ok300** [comment]
Fixed by #896
