### ISSUE TITLE
Payment asynchronicity

### ISSUE THREAD

**Issue by darioAnongba** [breez/breez-sdk#908]
Hi all,

i've been using the Breez SDK to implement an app that segregates the underlying node into accounts. Similar to LNBits, it is possible to create multiple accounts that share the same underlying node, each with its own balance and permissions.

When implementing the "outgoing payment" functionality, I noticed that I can run into concurrency issues between the moment the payment is sent and the moment the event is received because the sending function returns the payment_hash only after the payment has been processed.

In order to implement the account functionality, I need to correlate the payment with a user account, so I need to save the payment in DB and then be able to find it back once it is received in an event. The reason is that if a payment is sent and then we crash, once the event is read upon restart, we won't be able to correlate it with a user. 

What I would like:
- A way to add labels to a payment so I can add a unique payment identifier that is different than the `payment_hash`, and retrieve it in the event that would have these labels `attached`.
- An asynchronous function that sends the payment but does not wait for its success and returns the `payment_hash`.
- any a similar solution enabling payment asynchronicity.

I noticed that the `Payment` returned when the function is successful in `LnUrlPayResult` does not contain all the `Payment` details in a similar way than the event `PaymentSucceed`, so I need the event even in the event where we implement it synchronously.

**Comment by roeierez** [comment]
Hi @darioAnongba you can save the payment hash before invoking send by parsing the paid bolt11.
Will that work?

**Comment by darioAnongba** [comment]
Hi,

The `LnUrlPayRequestData` does not contain a `payment_hash` field, nor does the InputType::NodeId. It seems this will only work for InputType::Bolt11. I don't have a unique identifier after using the `parse` function for each type of input. Adding personal labels would be good.

**Comment by dangeross** [comment]
@roeierez would it help in this case to allow adding optional metadata to the `LnUrlPayRequest` which can then be added to the payment internally once the payment is complete (and before the event is triggered)?

**Comment by roeierez** [comment]
> @roeierez would it help in this case to allow adding optional metadata to the `LnUrlPayRequest` which can then be added to the payment internally once the payment is complete (and before the event is triggered)?

I think yes but for consistency we should add this optional field also to the other payment methods (bolt11, keyse d)

**Comment by darioAnongba** [comment]
thanks guys

**Comment by dangeross** [comment]
Thanks @darioAnongba. I've reopened this issue the support the failure case

**Comment by darioAnongba** [comment]
HI @dangeross, @roeierez , it seems that this omitted from the release 0.4.0.

**Comment by dangeross** [comment]
> HI @dangeross, @roeierez , it seems that this omitted from the release 0.4.0.

Hi @darioAnongba, unfortunately the fix didn't make it into 0.4.0, but there will be a 0.4.1(-rc1) very soon with it included. Sorry for the wait

**Comment by darioAnongba** [comment]
No problem, I just found out 0.4.1-rc1 and can use it, so all good.
