### ISSUE TITLE
Moonpay: Add ability to set custom redirectURL on complete

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk#911]
Allow the caller to set a custom ... , which can point to their own custom landing page or in-app view.

https://github.com/breez/breez-sdk/blob/e541135b0f1fa90f964829444cb34d53251660e5/libs/sdk-core/src/moonpay.rs#L24

**Comment by roeierez** [comment]
duplicate of https://github.com/breez/breez-sdk/issues/912
