### ISSUE TITLE
JSON output for dev commands

### ISSUE THREAD

**Issue by simongltr** [breez/breez-sdk#939]
Hey,

We would like to use the data from dev commands in the settings of our app to debug our users. 

The issue is that the current format is a stringified rust structure, which is unusable for us. We can try to convert it to JSON but if we can get it directly from the SDK it would be simpler.

Thanks,
Simon

**Comment by ok300** [comment]
Thanks for the report @simongltr .

A solution for this is in the works and should be ready soon, I'll link it below when it's available.
