### ISSUE TITLE
Missing InvoicePaid events

### ISSUE THREAD

**Issue by darioAnongba** [breez/breez-sdk#996]
Hi all,

I believe this bug could be related to Greenlight `gl-plugin` instead of Breez but opening here first as the dependency of our app is the Breez SDK.

Recently, issues appeared with Greenlight where the node was not reachable and could not receive payments. After waiting some days, it seems to have been fixed but for some reason some events are not received anymore. Specifically the `InvoicePaid` event. 

The payment succeeds and the node receives the funds but no event is fired. The payment is displayed successfully with the correct status when calling `list_payments`. 

`Sync` and `NewBlock` events work fine.

Version `v0.4.2-rc2`.

**Comment by roeierez** [comment]
Your analysis is correct . We are waiting for a fix in greenlight.

**Comment by cdecker** [comment]
The fix here is in https://github.com/Blockstream/greenlight/pull/457, which is still a PR on the client side, since we want to verify v24.02 working before releasing to everybody, but it is already deployed on the servers.

The invoice payment notifications should be flowing again. Please confirm.

**Comment by darioAnongba** [comment]
Hi @cdecker, just tested and no, events are not received.

**Comment by cdecker** [comment]
Yep, we found another parser issue, deploying fixes now 👍

**Comment by darioAnongba** [comment]
events are received
