### ISSUE TITLE
Making validate_lnurl_pay public

### ISSUE THREAD

**Issue by darioAnongba** [breez/breez-sdk#998]
Hi all,

It seems that the `validate_lnurl_pay` function of the SDK (Rust) is a standalone function that can be made public as it is generic. It looks a lot like the `parse` function and could be beneficial to many apps that can use it even without using the `BreezServices`. 

What do you think ? 

Cheers,

**Comment by roeierez** [comment]
Indeed. We are about to extract out some generic logic (including these functions) to a different crate which the sdk will depend on so the functionality will be exposed as public.

**Comment by darioAnongba** [comment]
If I may add my 2 cents from the experience gained from implementing the SDK:
- Decoding the SuccessAction with the `payment_preimage` deserves to be part of the public package as well (reason below)

- Having a `lnurl_pay` function that does multiple steps in the background seems to not be the ideal behaviour because the validation of the input happens inside the function, which forces it to return an object with multiple possible error types (`LnUrlPayResult`). The steps for LNURL pay are:
  1. parse
  2. validate_lnurl_pay
  3. send_payment (normal bolt11 one) from a `CallbackResponse`
  4. decode_success_action
  
As you can see, only step iii. is an adapter action on the actual node. Currently the function can either fail with  `LnUrlPayError` or succeed with an object that itself can be 2 different types of errors. Also, the payment can succeed and the function still fail because of line 420: `sha256::Hash::from_str(&details.payment_preimage)?;` or line 445: `self.persister.insert_payment_external_info`.

All of that to say that `lnurl_pay` should probably be a function that accepts a `CallbackResponse` and does nothing else. Up to the user to generate that `CallbackResponse` using the public `parse` and `validate_lnurl_pay`. This way, the payment that happens externally and the validation are separated.

**Comment by ok300** [comment]
Related to #668.
